### ISSUE TITLE
don't hardcode pytest version

### ISSUE THREAD

**Issue by ignatenkobrain** [mozilla/bleach#244] opened 2017-01-02 01:07 UTC
Having `==3.0.3` doesn't make any sense and creates problem for packaging.

**Comment by willkg** [comment] 2017-02-18 02:25
pytest is only in the `requirements.txt` file which is intended for developers or people hacking on bleach to set up an environment for development. I'm not sure why pinning versions in that file (which helps development) affects packaging for users.

Can you elaborate?

**Comment by willkg** [comment] 2017-03-08 14:51
I'm not sure what the issue is here, so I'm going to close it out.

**Closed by willkg** 2017-03-08 14:51 UTC
Labels: needs-your-help
