### ISSUE TITLE
Mangles unclosed tags

### ISSUE THREAD

**Issue by gavinwahl** [mozilla/bleach#285] opened 2017-05-03 00:21 UTC
The string `<foo>` is getting cleaned to `&lt;foo&gt;&lt;/foo&gt;`. I expect it to be cleaned to `&lt;foo&gt;`.

It seems that the tag is getting closed before being entitized?

**Comment by willkg** [comment] 2017-05-03 01:46
This is a duplicate of #280.

Do you have real-world examples where this behavior causes problems? If so, can you add a comment to #280 with them?

Thank you!

**Closed** 2017-05-03 06:13 UTC
