### ISSUE TITLE
Double Angle Brackets defeat bleach

### ISSUE THREAD

**Issue by michaelwilson** [mozilla/bleach#245] opened 2017-01-07 01:38 UTC
If I attempt to `bleach.clean(..., attributes=[], tags=[], styles=[])` this string:

```
<<How The Grinch Stole Christmas>>
```

I get:

```
<<How The="" Grinch="" Stole="" Christmas="">>
```

It seems like the empty whitelist for attributes is being ignored for the inner `<...>`?

Thanks!

**Comment by willkg** [comment] 2017-01-07 02:58
I can't reproduce this. I get this:

```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import bleach
>>> bleach.clean('<<How The Grinch Stole Christmas>>')
u'&lt;&lt;how the="" grinch="" stole="" christmas=""&gt;&gt;'
>>> bleach.clean('<<How The Grinch Stole Christmas>>', attributes=[], tags=[], styles=[])
u'&lt;&lt;how the="" grinch="" stole="" christmas=""&gt;&gt;'
>>> 
```

That's with Python 2.7.12, bleach 1.5, and html5lib 0.9999999 (7 9s).

What're you using?

**Comment by michaelwilson** [comment] 2017-01-07 03:02
I'm using Python 2.7.11, but  would expect:

u'&lt;&lt;How The Grinch Stole Christmas &gt;&gt;'

**Comment by willkg** [comment] 2017-01-07 03:03
What version of bleach and html5lib are you using?

Also, why would you expect the angle brackets to not get escaped?

**Comment by michaelwilson** [comment] 2017-01-07 03:05
bleach (1.5.0)

html5lib (0.9999999)

Actually you’re correct, I’d expect both the inner and outer angle brackets to be escaped, sorry!

**Comment by willkg** [comment] 2017-01-07 03:07
Ok... So it seems like everything is fine except that you'd rather the words in the `<<...>>` weren't getting converted into a `foo=""` form. Is that right?

**Comment by michaelwilson** [comment] 2017-01-07 03:09
Yes, that’s the issue, I don't expect the foo=“” form.

**Comment by willkg** [comment] 2017-01-07 03:10
Ok. That seems like it's covered in part by issue #157. It's possible a future version of html5lib fixes this, but I haven't tested that out.

In the meantime, I'm going to close this out in favor of #157 because I think if that gets solved, it'll cover this, too.

**Closed by willkg** 2017-01-07 03:10 UTC

**Comment by michaelwilson** [comment] 2017-01-07 03:15
Tried the following:


--(2214:Fri,06 Jan 17:$)-- pip install html5lib --upgrade
Collecting html5lib
  Using cached html5lib-0.999999999-py2.py3-none-any.whl
Requirement already up-to-date: six in ./Virtualenvs/fyndit/lib/python2.7/site-packages (from html5lib)
Requirement already up-to-date: webencodings in ./Virtualenvs/fyndit/lib/python2.7/site-packages (from html5lib)
Collecting setuptools>=18.5 (from html5lib)
  Using cached setuptools-32.3.1-py2.py3-none-any.whl
Installing collected packages: setuptools, html5lib
  Found existing installation: setuptools 32.1.0
    Not uninstalling setuptools at /usr/local/lib/python2.7/site-packages, outside environment /Users/michael/Virtualenvs/fyndit/bin/..
  Found existing installation: html5lib 0.9999999
    Uninstalling html5lib-0.9999999:
      Successfully uninstalled html5lib-0.9999999
Successfully installed html5lib-0.999999999 setuptools-32.3.1
(fyndit)--(michael@macpro-2016)-(/Users/michael)--
--(2214:Fri,06 Jan 17:$)-- pip install bleach --upgrade
Requirement already up-to-date: bleach in ./Virtualenvs/fyndit/lib/python2.7/site-packages
Requirement already up-to-date: six in ./Virtualenvs/fyndit/lib/python2.7/site-packages (from bleach)
Collecting html5lib!=0.9999,!=0.99999,<0.99999999,>=0.999 (from bleach)
Installing collected packages: html5lib
  Found existing installation: html5lib 0.999999999
    Uninstalling html5lib-0.999999999:
      Successfully uninstalled html5lib-0.999999999
Successfully installed html5lib-0.9999999
(fyndit)--(michael@macpro-2016)-(/Users/michael)--
--(2214:Fri,06 Jan 17:$)-- python
Python 2.7.11 (default, Jan 22 2016, 08:29:18)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bleach
>>> bleach.clean('<<How The Grinch Stole Christmas>>', attributes=[], tags=[], styles=[])
u'&lt;&lt;how the="" grinch="" stole="" christmas=""&gt;&gt;'
>>>

**Comment by michaelwilson** [comment] 2017-01-07 03:16
Sorry, should have read more carefully. Will wait for #157.
'
