### ISSUE TITLE
Linkify doesn't successfully remove attrs

### ISSUE THREAD

**Issue by purpleshiny** [mozilla/bleach#246] opened 2017-01-24 16:17 UTC
```
import bleach

def fix_up_links(attrs, new=False):
    attrs.pop("target", None)
    return attrs

print(bleach.linkify("<a href='http://google.com' target='foo'>link</a>",
    callbacks=[fix_up_links]))
```
For me, the output of this is:
```
<a href="http://google.com" target="foo">link</a>
```

I'm using version 1.5.0. The [documentation](http://pythonhosted.org/bleach/linkify.html#removing-attributes) led me to believe that the output of this should be `<a href="http://google.com">link</a>`. I'm on OSX (Sierra) if that matters.

**Comment by willkg** [comment] 2017-01-24 16:22
I haven't verified or looked into what you're saying. I'm in the middle of overhauling bleach to work with html5lib >= 0.99999999.

Can anyone else verify this behavior and/or look into it?

**Comment by willkg** [comment] 2017-03-04 14:58
I'm rewriting linkify now. With that code, I can't reproduce this:

```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import bleach
>>> def fix_up_links(attrs, new=False):
...     attrs.pop((None, 'target'), None)
...     return attrs
... 
>>> print(bleach.linkify('<a href="http://example.com" target="foo">link</a>', callbacks=[fix_up_links]))
<a href="http://example.com">link</a>
>>> 
```

So if this was an issue, it'll be gone in 2.0.

**Comment by willkg** [comment] 2017-03-04 16:07
I landed the linkify rewrite, so closing this out.

**Closed by willkg** 2017-03-04 16:07 UTC
Labels: linkify
