### ISSUE TITLE
bug: CSS styles starting with a dash are not supported (-webkit-xxx, etc.)

### ISSUE THREAD

**Issue by boiseau** [mozilla/bleach#623] opened 2021-12-13 10:14 UTC
**Describe the bug**

- Whitelisting does not work for CSS styles that starts with a dash (-webkit-text-size-adjust, etc.)
- In that case, Bleach removes all CSS styles of the HTML elements

** Versions:**

 - Python Version: 3.9
 - Bleach Version: 4.1.0

**To Reproduce**

```
import bleach
content = '<div style="color:black; -webkit-text-size-adjust:100%"></div>'
print(bleach.clean(content,tags=['div'],attributes={"*":["style"]},styles=['color','-webkit-text-size-adjust']))
```
**Actual behavior**

`<div style=""></div>`

**Expected behavior**

`<div style="color: black; -webkit-text-size-adjust: 100%;"></div>`

**Fixing suggestion**

- Add `\-` in bleach/sanitizer.py, line 618

Before:
`[/:,#%!.\s\w]`

After:
`[/:,\-#%!.\s\w]`

**Comment by willkg** [comment] 2021-12-13 20:00
Thank you for writing this up!

This is a duplicate of issue #529. I think fixing that it stalled on reworking `sanitize_css` to use a real style parser which is covered in issue #248 .

I'm going to close this out in favor of those.

**Closed by willkg** 2021-12-13 20:00 UTC
Labels: untriaged
